name: CI-Client

on:
  pull_request:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Skip React CI
        run: echo "No React CI yet"
