name: CI-Python

on:
  pull_request:
    paths:
      - 'server/recommender-api/**'
    branches:
      - main

jobs:
  python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/recommender-api
    steps:
      - name: Skip Python CI
        run: echo "No Python CI yet"
